<style>
    .item{
        margin-top: 10px;
        margin-right: 20px;
    }
</style>
<div class="container">
        <div class="item">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Feature1.png'); ?>" alt="Mô tả ảnh" />
        </div>
        <div class="item">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Feature2.png'); ?>" alt="Mô tả ảnh" />
        </div>
        <div class="item">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Feature3.png'); ?>" alt="Mô tả ảnh" />
        </div>
        <div class="item">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Feature4.png'); ?>" alt="Mô tả ảnh" />
        </div>
    </div>
