<footer>
    <section class="footer-top">
        <div class="footer-col">
            <ul>
                <li>QUICK LINKs</li>
                <li>Terms & Conditions</li>
                <li>Privacy Policies</li>
                <li>Delivery - Return - Warranty</li>
                <li>Payment Methods</li>
                <li>Loyalty Program</li>
            </ul>
        </div>
        <div class="footer-col">
            <ul>
                <li>COMPANY</li>
                <li>About Us</li>
                <li>FAQs</li>
                <li></li>
                <li></li>
            </ul>
        </div>
        <div class="footer-col">
            
        </div>

        <div class="footer-col">
            
        </div>
    </section>
    <div class="copyright">

    </div>
</footer>