
<div class="container">

    <div class="banner-left">
        
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Artboard.png'); ?>" alt="imgpanelheader" />

    </div>

    <div class="banner-right">
        <div class="banner-right-top">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Artboard1.png'); ?>" alt="Mô tả ảnh" />
        </div>
        <div class="banner-right-bottom">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Artboard2.png'); ?>" alt="Mô tả ảnh" />
        </div>
    </div>
</div>

