<div class="container-new">
    <div class="container-new-top">
        <div class="new-top-left">
            <h1>News</h1>
        </div>
        <div class="new-top-rigth">

            <div class="item-rigth">
                <h5>ReviewProduct</h5>
            </div>

            <div class="item-rigth">
                <h5>Tips&Tricks</h5>
            </div>

            <div class="item-rigth">
                <h5>Promotions</h5>
            </div>

            <div class="item-rigth">
                <h5>ViewAll</h5>
            </div>


        </div>
    </div>

    <div class="container-new-bottom">
        <div class="item-new">
            <div class="image">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new.png'); ?>" alt="Mô tả ảnh" />
            </div>

            <div class="new-content">
                <h3>How To Make A Fresh Juice Blended For Your Family?</h3>
            </div>
            <button class="click">Organic</button>
        </div>

        <div class="item-new">
            <div class="image">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new-1.png'); ?>" alt="Mô tả ảnh" />
            </div>

            <div class="new-content">
                <h3>Fresh Eggs Caroline In Australia Villages</h3>
            </div>
            <div class="button">
                <button class="click">Organic</button>
            </div>
        </div>

        <div class="item-new">
            <div class="image">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new-2.png'); ?>" alt="Mô tả ảnh" />
            </div>

            <div class="new-content">
                <h3>Discover Fresh Organic Farms In Switzeland Villages</h3>
            </div>
            <button class="click">Organic</button>
        </div>

        <div class="item-new">
            <div class="image">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new-3.png'); ?>" alt="Mô tả ảnh" />
            </div>

            <div class="new-content">
                <h3>B&O Play - Best Headphone For You</h3>
            </div>
            <button class="click">Organic</button>
        </div>
    </div>


</div>
