<div class="container-card">

    <h1>Deals Of The Day</h1>

    <div class="container-card-1">
        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product Card.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product Card.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product Card.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product Card.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product Card.png'); ?>" alt="Mô tả ảnh" />
        </div>
    </div>
</div>
<style>
    .container-card-1 {
        display: flex;
    }

</style>