<div class="container-seller">
    <div class="item-content">
    <h1><?= $block->getData('Cirtus Juicer') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>

    <div class="item-content">
    <h1><?= $block->getData('Blender') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>
    <div class="item-content">
    <h1><?= $block->getData('Eletric Oven') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>
    <div class="item-content">
    <h1><?= $block->getData('Air Purifier') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>
    <div class="item-content">
    <h1><?= $block->getData('Air-Conditioner') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>
    <div class="item-content">
    <h1><?= $block->getData('Refriregator') ?></h1>
        <div class="item-seller">
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
            </div>
            <div class="item-1">
                <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
            </div>
        </div>
    </div>


</div>
