<div class="container-seller">
    <div class="container-content">
        <h1>Best Seller</h1>
    </div>
    <div class="container-seller-1">
        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-1.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-2.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-3.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-1">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Rectangle 9-4.png'); ?>" alt="Mô tả ảnh" />
        </div>
    </div>

</div>
<style>
    .container-seller-1 {
        display: flex;
    }
    
</style>