<div class="container-product">
<div class="container-content">
        <h1>Your Recently Viewed Products</h1>
    </div>
    <div class="container-product-1">
        <div class="item-product">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-product">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product-1.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-product">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product-2.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-product">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product-3.png'); ?>" alt="Mô tả ảnh" />
        </div>

        <div class="item-product">
            <image src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Product-4.png'); ?>" alt="Mô tả ảnh" />
        </div>
    </div>
    
</div>
<style>
    .container-product-1 {
        display: flex;
    }

    .item-product{
        margin: 0 20px 0 20px;
    }
</style>